### ISSUE TITLE
Delete user

### ISSUE THREAD

**Issue by murwaneisa** [murwaneisa/HKIF-SERVER#30]
Dependent Branch(es)
feature/delete-user

Functionality
implement user delete on the server, super admin can delete   user that  has a membership type of GUEST 

Additional Notes

**Comment by zzfz1** [comment]
@murwaneisa 

"delete user that has a membership type of GUEST"

Now that membershipType has been changed to UNPAID, not sure when has it been changed.

![image](https://github.com/murwaneisa/HKIF-SERVER/assets/86393880/6b03c964-cf31-46a7-8851-2274f3dc13c2)
